name: Wrangler Publish

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      
      - name: Build Worker
        run: |
          ./gradlew buildWorker --stacktrace
          
      - name: Deploy to Cloudflare Workers with Wrangler
        uses: cloudflare/wrangler-action@1.2.0
        env:
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          # CF_ZONE_ID: {{ secrets.CF_ZONE }}
        with:
          # Your Cloudflare API Token
          apiToken: ${{ secrets.API_TOKEN }}
